/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeviceDeviceIdVacancyPost$Params {

/**
 * The ID of the device that should be set to vacancy mode.
 */
  deviceId: string;
      body: {

/**
 * The duration (in days) of the vacancy
 */
'duration'?: number;
}
}

export function deviceDeviceIdVacancyPost(http: HttpClient, rootUrl: string, params: DeviceDeviceIdVacancyPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, deviceDeviceIdVacancyPost.PATH, 'post');
  if (params) {
    rb.path('deviceId', params.deviceId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

deviceDeviceIdVacancyPost.PATH = '/device/{deviceId}/vacancy';
