/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HumidityHistory } from '../../models/humidity-history';

export interface DeviceDeviceIdHistoryHumidityPost$Params {

/**
 * The ID of the device whose humidity history should be retrieved
 */
  deviceId: string;
      body: {

/**
 * The start of the interval as a timestamp in seconds
 */
'startTimestamp'?: number;

/**
 * The end of the interval as a timestamp in seconds
 */
'endTimestamp'?: number;
}
}

export function deviceDeviceIdHistoryHumidityPost(http: HttpClient, rootUrl: string, params: DeviceDeviceIdHistoryHumidityPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<HumidityHistory>>> {
  const rb = new RequestBuilder(rootUrl, deviceDeviceIdHistoryHumidityPost.PATH, 'post');
  if (params) {
    rb.path('deviceId', params.deviceId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<HumidityHistory>>;
    })
  );
}

deviceDeviceIdHistoryHumidityPost.PATH = '/device/{deviceId}/history/humidity';
