/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DeviceInfoStripped } from '../../models/device-info-stripped';

export interface DeviceDeviceIdGet$Params {

/**
 * The ID of the device to retrieve
 */
  deviceId: string;
}

export function deviceDeviceIdGet(http: HttpClient, rootUrl: string, params: DeviceDeviceIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<DeviceInfoStripped>> {
  const rb = new RequestBuilder(rootUrl, deviceDeviceIdGet.PATH, 'get');
  if (params) {
    rb.path('deviceId', params.deviceId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DeviceInfoStripped>;
    })
  );
}

deviceDeviceIdGet.PATH = '/device/{deviceId}';
