/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Preset } from '../../models/preset';

export interface PresetsGet$Params {
}

export function presetsGet(http: HttpClient, rootUrl: string, params?: PresetsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Preset>>> {
  const rb = new RequestBuilder(rootUrl, presetsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Preset>>;
    })
  );
}

presetsGet.PATH = '/presets';
