/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DeviceInfo } from '../../models/device-info';

export interface RawDeviceDeviceIdGet$Params {

/**
 * The ID of the device to retrieve
 */
  deviceId: string;
}

export function rawDeviceDeviceIdGet(http: HttpClient, rootUrl: string, params: RawDeviceDeviceIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<DeviceInfo>> {
  const rb = new RequestBuilder(rootUrl, rawDeviceDeviceIdGet.PATH, 'get');
  if (params) {
    rb.path('deviceId', params.deviceId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DeviceInfo>;
    })
  );
}

rawDeviceDeviceIdGet.PATH = '/raw/device/{deviceId}';
