/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WeatherHistory } from '../../models/weather-history';

export interface WeatherRangePost$Params {
      body: {

/**
 * The start of the interval as a timestamp in seconds
 */
'startTimestamp'?: number;

/**
 * The end of the interval as a timestamp in seconds
 */
'endTimestamp'?: number;

/**
 * The device whose history is being viewed. Used to prevent extra past data from being loaded.
 */
'deviceId'?: string;
}
}

export function weatherRangePost(http: HttpClient, rootUrl: string, params: WeatherRangePost$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WeatherHistory>>> {
  const rb = new RequestBuilder(rootUrl, weatherRangePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WeatherHistory>>;
    })
  );
}

weatherRangePost.PATH = '/weather/range';
