/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Device {
  dev_alias: string;
  dev_label: Array<string>;
  did: string;
  gw_did: number;
  host: string;
  is_disabled: boolean;
  is_low_power: boolean;
  is_online: boolean;
  is_sandbox: boolean;
  mac: string;
  mcu_hard_version: string;
  mcu_soft_version: string;
  mesh_id: number;
  passcode: string;
  port: number;
  port_s: number;
  product_key: string;
  product_name: string;
  protoc: number;
  remark: string;
  role: string;
  sleep_duration: number;
  state_last_timestamp: number;
  type: string;
  wifi_hard_version: string;
  wifi_soft_version: string;
  ws_port: number;
  wss_port: number;
}
