/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HeatingMode } from '../models/heating-mode';
import { HeatingSchedule } from '../models/heating-schedule';
import { SpecialMode } from '../models/special-mode';
export interface DeviceInfoStripped {
  comfortTargetTemperature: number;
  currentHumidity: number;
  currentMode: HeatingMode;
  currentSignal: HeatingMode;
  currentTemperature: number;
  ecoTargetTemperature: number;
  isHeating: boolean;
  isLocked: boolean;
  isUsingTimer: boolean;
  isWindowDetectionOn: boolean;
  mode: HeatingMode;
  schedule: Array<HeatingSchedule>;
  specialMode: SpecialMode;
  specialModeRemainingTime: number;
}
