/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DeviceStripped {
  deviceId: string;
  isOnline: boolean;
  macAddress: string;
  productName: string;
  readableName: string;
}
