/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum HeatingMode {
  Off = 'OFF',
  Comfort = 'COMFORT',
  Eco = 'ECO',
  FrostProtection = 'FROST_PROTECTION',
  Comfort1 = 'COMFORT_1',
  Comfort2 = 'COMFORT_2',
  Unknown = 'UNKNOWN'
}
