/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HeatingSchedule } from '../models/heating-schedule';
export interface PresetRequest {
  description?: string;
  name: string;
  schedule: Array<HeatingSchedule>;
}
