/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum SpecialMode {
  None = 'NONE',
  Vacancy = 'VACANCY',
  Boost = 'BOOST',
  MotionDetection = 'MOTION_DETECTION',
  Unknown = 'UNKNOWN'
}
